package es.udc.tfg.server.model.domain.Enumerados;

public enum Provincias{
  ALBACETE,ALICANTE,ALMERIA,ALAVA,ASTURIAS,AVILA,BADAJOZ,ISLAS_BALEARES,BARCELONA,
  BIZKAIA,BURGOS,CACERES,CADIZ,CANTABRIA,CASTELLON,CIUDAD_REAL,CORDOBA,A_CORUNA,CUENCA,
  GIPUZKOA,GIRONA,GRANADA,GUADALAJARA,HUELVA,HUESCA,JAEN,LEON,LLEIDA,LUGO,MADRID,MALAGA,
  MURCIA,NAVARRA,OURENSE,PALENCIA,LAS_PALMAS,PONTEVEDRA,LA_RIOJA,SALAMANCA,
  SANTA_CRUZ_DE_TENERIFE,SEGOVIA,SEVILLA,SORIA,TARRAGONA,TERUEL,TOLEDO,VALENCIA,VALLADOLID,
  ZAMORA,ZARAGOZA,CEUTA,MELILLA,
}
